CC  = gcc
LIBS = -lblas
OPT = -ansi -Wall
OBJS = disp.c

ex01: ex01.c
	$(CC) $< $(OBJS) $(LIBS) $(OPT) -o $@ 

ex02: ex02.c
	$(CC) $< $(OBJS) $(LIBS) $(OPT) -o $@ 

ex03: ex03.c
	$(CC) $< $(OBJS) $(LIBS) $(OPT) -o $@ 

ex04: ex04.c
	$(CC) $< $(OBJS) $(LIBS) $(OPT) -o $@ 

ex05: ex05.c
	$(CC) $< $(OBJS) $(LIBS) $(OPT) -o $@ 

ex06: ex06.c
	$(CC) $< $(OBJS) $(LIBS) $(OPT) -o $@ 

ex07: ex07.c
	$(CC) $< $(OBJS) $(LIBS) $(OPT) -o $@ 

ex08: ex08.c
	$(CC) $< $(OBJS) $(LIBS) $(OPT) -o $@ 

ex09: ex09.c
	$(CC) $< $(OBJS) $(LIBS) $(OPT) -o $@ 

ex10: ex10.c
	$(CC) $< $(OBJS) $(LIBS) $(OPT) -o $@ 
